### ISSUE TITLE
kubewarden policies - generic actions

### ISSUE THREAD

**Issue by flavio** [kubewarden/github-actions#4]
Language agnostic actions to be created 

* [x] install kwctl
* [ ] release

**Comment by viccuad** [comment]
Initial contribution done by pair programming and a push to Superseded by https://github.com/kubewarden/github-actions/tree/v1.

**Comment by viccuad** [comment]
RC is there: ghcr.io/kubewarden/policies/allowed-fsgroups-psp:v0.1.3
Closing as done.
