### ISSUE TITLE
Ignore comments in the artifacthub-pkg.yml file comparison

### ISSUE THREAD

**Issue by jvanz** [kubewarden/github-actions#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When releasing policies with custom comment headers in the `artifacthub-pkg.yml` file the CI fails. In our current [script](https://github.com/kubewarden/github-actions/blob/3468846b62f436d52334b0f63685b5dcc399a423/check-artifacthub/action.yml#L25-L46), we use `git diff` to ensure that the generate file in the CI matches the file in the repository. However, when used custom comment headers the files will always differ. Because `kwctl` adds a hard coded comment header.

### Expected Behavior

The comparison script should take only the yaml content in account. Ignoring the comments in the `artifacthub-pkg.yaml` file

### Steps To Reproduce

Try to release the community policy [`probes-policy`](https://github.com/nlamirault/probes-policy)

### Environment

```markdown
- OS:
- Architecture:
```

### Anything else?

This is preventing us from publishing the following community policies on artifacthub.io:
- https://github.com/nlamirault/probes-policy
- https://github.com/nlamirault/disallow-default-namespace-policy/

**Comment by flavio** [comment]
I was thinking about updating this check:

https://github.com/kubewarden/github-actions/blob/3468846b62f436d52334b0f63685b5dcc399a423/check-artifacthub/action.yml#L38-L45

I tried adding a `--ignore-matching-lines '^#'` but it didn't work... I tried some other regexps (which would work in other languages), but none of them worked :/

**Comment by flavio** [comment]
@viccuad can you help maybe with the `ignore-matching-lines` regexp please?

**Comment by flavio** [comment]
Another option would be to add this comparison feature to kwctl itself. We could convert the yaml contents to json, then use the [assert-json-diff](https://crates.io/crates/assert-json-diff) library to perform the comparison.

However, in this case we would have to add some git related code to kwctl... :thinking: 

I just want this whole artifacthub scaffold story to be over, so let's go with the easiest solution...

**Comment by viccuad** [comment]
Implemented the `ignore-matching-lines` in the linked PR, which I think should get in nevertheless.

There seem to be 2 approaches:
1. Be able to compare hand-crafted `artifacthub-pkg.yml` against checked-in versions: We would need `yq compare`, as YAML fields can change order. But given that `artifacthub-pkg.yml` is hand crafted, there's little benefit, the user needs to bump and check all fields manually anyways.
2. Be able to compare automaticaly created `artifacthub-pkg.yml`, created via `kwctl scaffold` & `make` targets. We can keep using `git diff`. 

The PRs opened against community policies follow number 2, so the git diff fix should be enough.

**Comment by viccuad** [comment]
Tagged github-actions as `v3.1.1`.
